### ISSUE TITLE
[Question] Does this work with windows ?

### ISSUE THREAD

**Issue by iceman2894** [mnvx/lowrapper#14]
Does this work with windows ?

**Comment by mnvx** [comment]
I has not tried. You may try to specify $binaryPath to libreoffice exe file.

```php
$converter = new Converter('c:\path\to\libreoffice.exe');
```

**Comment by iceman2894** [comment]
> I has not tried. You may try to specify $binaryPath to libreoffice exe file.
> 
> ```
> $converter = new Converter('c:\path\to\libreoffice.exe');
> ```

Thanks for replying back,

I got it working with windows by:

- adding `C:\Program Files\LibreOffice\program\soffice.exe` to system PATH variable in windows
- using `$converter = new Converter('soffice', realpath(__DIR__."/convertTmp/");`

*had some permission errors when i didn't specify another temp dir than the windows default*
