### ISSUE TITLE
Временный файл

### ISSUE THREAD

**Issue by tumasst** [mnvx/lowrapper#3]
Доброго времени суток,

Заметил, что при генерации не удаляется временный файл, как понимаю за это отвечает метод `deleteInput` в `Converter.php`

Собственно после изменения на `if ($param...)` всё работает корректно, временный файл удаляется.
Или задумка была в чём-то ином ? 

Спасибо за обёртку!

**Comment by mnvx** [comment]
Похоже вы правы. Позже перепроверю этот момент. Спасибо.

**Comment by mnvx** [comment]
Посмотрел проект - описанная выше идея была раньше, но в действительности временный файл пришлось создавать всегда, чтобы не было проблем с правами доступа. Поэтому убрал условие. Спасибо. что заметили.

**Comment by tumasst** [comment]
Да, я делал также, ещё с версии либры 4.2, но я тогда делал через phpseclib/SSH. Сейчас решил обновить данный функционал и удачно наткнулся на вашу статью на хабре и соответственно на вашу разработку. Обновил либру и использую вашу обёртку, пока всё отлично :) 

Спасибо Вам, сэкономили время)
