### ISSUE TITLE
Converting html to xls russian symbols

### ISSUE THREAD

**Issue by kosuhin** [mnvx/lowrapper#6]
Hi, did you have any problems with the converting of russian characters in the xls file? I have a broken encoding
![image](https://user-images.githubusercontent.com/13706149/43589258-fd2ce878-9676-11e8-9c26-a75a1e5ac301.png)

**Comment by mnvx** [comment]
Did you convert HTML to XLS? What encoding did you specify in HTML? Show please example of HTML.

**Comment by kosuhin** [comment]
Thanks for the answer!
I'm passing HTML like this
```php
->setInputData ('<html lang = "en-RU"><meta charset = "UTF-8">'. $html. '</ html>')
```
And $html variable contains table with russian words.

**Comment by mnvx** [comment]
I have not problems with russian symbols. I use next code for converting:

    $converter = App::make(ConverterInterface::class);
    $parameters = (new LowrapperParameters())
        ->setInputData($source)
        ->setOutputFile(config('excel.export.store.path') . DIRECTORY_SEPARATOR . $serverFileName)
        ->setOutputFormat(Format::SPREADSHEET_XLS);
    $converter->convert($parameters);

As you can see I don`t use any filters. In my case data in `$source` is in UTF-8 encoding. How you obtained data into `$html` variable? If this variable was composed from database data, will be good to check client encoding of connection, encoding of database table. So, check what your `$html` string contains data in UTF-8 encoding.

**Comment by kosuhin** [comment]
Hi.
I created simple repository for example
https://github.com/kosuhin/test_lowrapper

Here is my test.html file - https://github.com/kosuhin/test_lowrapper/blob/master/test.html
And here is my PHP script - https://github.com/kosuhin/test_lowrapper/blob/master/index.php

And this is my result
![image](https://user-images.githubusercontent.com/13706149/43626914-a6c856d0-96fc-11e8-9149-9f19df23b233.png)

But if I use such $parameters:
```php
$parameters = (new LowrapperParameters())
    ->setInputFile(__DIR__.'/test.html')
    ->setOutputFormat(Format::SPREADSHEET_HTML)
    ->setOutputFile(__DIR__.'/result.xls');
```
I get such result.
![image](https://user-images.githubusercontent.com/13706149/43626995-0fb5e2de-96fd-11e8-9e8d-3a1d99f8681e.png)

**Comment by mnvx** [comment]
I has cloned your test project. If I run code without changes:

```php
<?php

require_once "vendor/autoload.php";

use Mnvx\Lowrapper\Converter;
use Mnvx\Lowrapper\LowrapperParameters;
use Mnvx\Lowrapper\Format;

$converter = new Converter();
$parameters = (new LowrapperParameters())
    ->setInputFile(__DIR__.'/test.html')
    ->setOutputFormat(Format::SPREADSHEET_XLS)
    ->setOutputFile(__DIR__.'/result.xls');
$converter->convert($parameters);
```

I have next correct result:

![image](https://user-images.githubusercontent.com/829880/43633762-d3ab7df6-9712-11e8-8f28-58cf3c1790c8.png)

About my environment.

```bash
$ libreoffice --version
LibreOffice 6.0.3.2 00m0(Build:2)

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```

Ubuntu 18.04.

Maybe it will helps...

**Comment by kosuhin** [comment]
thanks, I will check

**Comment by kosuhin** [comment]
Hm. It seems what in LibreOffice 6 all is right
![image](https://user-images.githubusercontent.com/13706149/43642515-8feb0c80-9730-11e8-8cd9-e0c78046d5e0.png)
Thank you for your answers
