### ISSUE TITLE
Error in annotations in incoming parameters

### ISSUE THREAD

**Issue by AndreyNegrov** [mnvx/lowrapper#8]
in https://github.com/mnvx/lowrapper/blob/master/src/LowrapperParameters.php:113 input parameter is NULL. My codeanalyzer(PSALM) thinks this is a mistake. Maybe there should be 'string|null'

**Comment by mnvx** [comment]
Yes, correct phpdoc is `@param string|null $outputFormat`

**Comment by AndreyNegrov** [comment]
А можете поправить, а то не могу проект собрать, ругается коданализатор. Заранее благодарен

**Comment by mnvx** [comment]
Я смотрю аналогичные проблемы и в других строчках:

https://github.com/mnvx/lowrapper/blob/master/src/LowrapperParameters.php#L127

https://github.com/mnvx/lowrapper/blob/master/src/LowrapperParameters.php#L135

Если не сложно, сделайте pull request. Заодно наверняка еще что-то выловите аналоизатором.

**Comment by AndreyNegrov** [comment]
ок

**Comment by AndreyNegrov** [comment]
Пул реквест не проходит(
Can't Create Pull Request
			Push failed:
			Fatal: HttpRequestException encountered.
			unable to access 'https://github.com/mnvx/lowrapper.git/': The requested URL returned error: 403

**Comment by mnvx** [comment]
Надо форкнуть репозиторий, запушить изменения в свой репозиторий и нажать в интерфейсе гитхаба кнпоку для создания пул реквеста

**Comment by AndreyNegrov** [comment]
Готово

**Comment by AndreyNegrov** [comment]
Отредактировал пул реквест. В php 5.5 не поддерживается указание типов через или, поэтому пришлось выпилить типы из аннотаций

**Comment by mnvx** [comment]
Changes are included in release 1.0.3
